### ISSUE TITLE
error: password authentication failed for user

### ISSUE THREAD

**Issue by icetee** [atom/teletype-server#34] opened 2017-11-15 23:27 UTC
If you are running on your own server, you may also need the following environment variables for PostgreSQL:

**PGDATABASE=dbname
PGPASSWORD=password
PGUSER=username**

**Comment by jasonrudolph** [comment] 2017-11-16 01:45
@icetee: Can you tell us more about the steps necessary to reproduce the issue that you ran into?

**Comment by icetee** [comment] 2017-11-16 02:18
I followed the steps and requirements listed in README.md. It has a simple VPS, I installed PostgreSQL. When I wanted to start the server, it ran because it did not find the password in the environment variables.

It was not entirely trivial to me. It may be supplement to README.md.

**Comment by jasonrudolph** [comment] 2017-11-16 20:55
Thanks for the additional info. 

> It may be supplement to README.md.

Cool. Would you be up for opening a pull request to update the README for future developers that are running their own server?

Since it sounds like you've figured out the solution to the problem, I'm going to close this issue. But if you want to open a pull request to supplement the README, I'll be happy to review that pull request and try to help you get it merged.

**Closed by jasonrudolph** 2017-11-16 20:55 UTC
